version: '2'
services:
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb:/data/db
    restart: always
    networks:
      - elk
    expose:
      - 6016
    ports:
      - "27017:27017"

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    hostname: adminmongo
    networks:
      - elk
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0

  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: jupyter
    hostname: jupyter
    networks:
      - elk
    ports:
      - "8889:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./jupyter:/home/jovyan/work
    depends_on:
      - mongo
      - mysql
    links:
      - mongo
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3306"
    networks:
      - elk
    environment:
      - MYSQL_ROOT_PASSWORD=iii
    volumes:
      - ./mysql_db/mysql_data:/var/lib/mysql
      - ./mysql_db/mysql_init:/docker-entrypoint-initdb.d/
  
networks:
  elk:
    driver: bridge
